### ISSUE TITLE
Regression Tasks

### ISSUE THREAD

**Issue by briankleinqiu** [berkeley-stat159/project-theta#41]
Let's use this to make clear what's going on with the regression files and all the related moving parts

**Comment by BenjaminHsieh** [comment]
#50

**Comment by BenjaminHsieh** [comment]
Also something to keep in mind going forward with our beta values in regression: it may not be too helpful to save the beta estimates as txt files in the 'data/ds005/...' directory, since it will be ignored by git. 
Perhaps we can combine the end beta results with heatmap/t-value/validation to create plot. 

The end goal of scripts should be some interpret-able plots

**Comment by BenjaminHsieh** [comment]
closing
