### ISSUE TITLE
Paper Fixes Before Friday

### ISSUE THREAD

**Issue by BenjaminHsieh** [berkeley-stat159/project-theta#47]
1. Need to change the title
2. Problem with reference not showing up
3. Need to add DATA section
4. Need to add RESULTS section

Question: should we break off the last section of "PLAN" into "DISCUSSION"?

**Comment by changsiyao** [comment]
I actually think in the final paper, explanation on why we simplified the model should stay with the model section. The discussion section is probably more for discussing the results we find. So, it's probably fine to leave everything in the PLAN section.
Also, I kinda want to keep a separate PLAN file just in case we want to refer back to it, especially since we will probably be updating all the other sections for the final paper.
Any other thought on it?

**Comment by BenjaminHsieh** [comment]
ok thats fine

**Comment by BenjaminHsieh** [comment]
I am adding some more details to data and have already fixed 1 & 2, do any of you guys have time to work on results? some specific explanations,findings so far, etc... Also, I think including some preliminary figures would be good (and would increase length of our paper lol). Thanks

**Comment by BenjaminHsieh** [comment]
also should I rename "plan" to "methods"? b/c the later in blank rn

**Comment by BenjaminHsieh** [comment]
oops *latter is

**Comment by BenjaminHsieh** [comment]
Also to do: 
80 character limit to the tex files

**Comment by changsiyao** [comment]
Great work!
A few minor changes, maybe? The last section, discussion of challenges is centered?
Also seems like, we have duplicate inferences on data section, section 3.1.5 and 3.3.4. Section 3.3.4 probably should be deleted.
And were we gonna talk about bonferroni correction? the word is in the report but nothing is following it, in section 3.1.5.

**Comment by BenjaminHsieh** [comment]
Sry guys I won't be at the computer again tonight, someone else can take a
look?

**Comment by BenjaminHsieh** [comment]
closing good work
